import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "source-code",
        name: "Source Code (Monolith)",
        icon: "📁",
        category: "service",
        runtime: "event-loop",
        position: { x: 60, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "Your source code: App.tsx imports Dashboard, AdminPanel, and Charts. Chart library, date-fns, lodash — all imported at the top of files. Without code splitting the bundler (Vite/Webpack) would combine EVERYTHING into one massive bundle.js. Every change to any file invalidates the entire bundle cache — users re-download everything even if only one file changed.",
    },
    {
        id: "bundler",
        name: "Vite Build (Bundler)",
        icon: "⚙️",
        category: "service",
        runtime: "blocking",
        position: { x: 280, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "The bundler (Vite uses Rollup, CRA uses Webpack) analyzes your import graph. For dynamic imports (import()) it creates SPLIT POINTS — separate output files called chunks. Static imports in the same entry file become part of the same chunk. The bundler also performs tree-shaking (removing unused exports) and minification. Vite automatically splits vendor libraries (node_modules) from application code.",
    },
    {
        id: "vendor-chunk",
        name: "vendor.js (React+libs)",
        icon: "📦",
        category: "database",
        runtime: "blocking",
        position: { x: 500, y: 80 },
        state: "idle",
        metadata: {},
        explanation: "The vendor chunk contains stable third-party libraries: React, ReactDOM, React Router, Zustand. These rarely change between deployments. By separating them: users download vendor.js once and it stays cached for months (long-term caching with content hash). Only your application code chunks change with each deployment — users re-download only those, not the vendor chunk.",
    },
    {
        id: "app-chunk",
        name: "main.js (App shell)",
        icon: "🏠",
        category: "database",
        runtime: "blocking",
        position: { x: 500, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "The main application chunk: App.tsx, routing setup, shared components, global state setup. This is small because routes are lazy-loaded. When you deploy a new version users re-download this chunk (it changed) but NOT the vendor chunk (it did not change). Content-hashed filename: main.a3f82b.js — same hash = browser cache hit, different hash = fresh download.",
    },
    {
        id: "route-chunks",
        name: "route chunks (Dashboard, etc)",
        icon: "🗂️",
        category: "database",
        runtime: "blocking",
        position: { x: 500, y: 360 },
        state: "idle",
        metadata: {},
        explanation: "Each route gets its own chunk via React.lazy: dashboard.1a2b3c.js, admin.4d5e6f.js, settings.7g8h9i.js. A user who only uses the dashboard never downloads admin.js. If only the dashboard changes in the new deployment, only dashboard.xyz.js gets a new hash — admin.js and settings.js remain cached. Granular caching: only changed pieces require re-download.",
    },
    {
        id: "http2-parallel",
        name: "HTTP/2 Parallel Download",
        icon: "⚡",
        category: "service",
        runtime: "event-loop",
        position: { x: 720, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "HTTP/2 multiplexing allows multiple small files to download in parallel over a single TCP connection — no head-of-line blocking. Splitting into 10 chunks of 50KB each can be faster than one 500KB file. HTTP/1.1 had 6 concurrent requests per domain limit. HTTP/2 removes this limit. Modern CDNs serve all chunks via HTTP/2. This makes fine-grained code splitting viable.",
    },
    {
        id: "runtime-loading",
        name: "Runtime Chunk Loading",
        icon: "🔄",
        category: "middleware",
        runtime: "event-loop",
        position: { x: 720, y: 380 },
        state: "idle",
        metadata: {},
        explanation: "At runtime React.lazy + dynamic import() request specific chunks on demand. The browser checks its cache first (by filename hash). If cached: instant. If not: HTTP request to CDN. React Suspense handles the loading state. Webpack/Vite inject a small runtime into the main chunk that manages chunk registration and loading coordination — the manifest file maps module IDs to chunk URLs.",
    },
];

const connections: Connection[] = [
    { id: "c1", source: "source-code", target: "bundler", protocol: "internal", latency: 10, reason: "vite build runs. Bundler analyzes the import graph, finds dynamic imports (React.lazy), creates split points." },
    { id: "c2", source: "bundler", target: "vendor-chunk", protocol: "internal", latency: 20, reason: "Third-party libs separated: react + react-dom + router = vendor.js. Content hash based on library versions. Stable across deployments." },
    { id: "c3", source: "bundler", target: "app-chunk", protocol: "internal", latency: 20, reason: "Application shell split: App.tsx + routing + shared components = main.js. Small because heavy routes are lazy." },
    { id: "c4", source: "bundler", target: "route-chunks", protocol: "internal", latency: 20, reason: "Each React.lazy import becomes a separate chunk. Dashboard, Admin, Settings each get their own hashed .js file." },
    { id: "c5", source: "app-chunk", target: "http2-parallel", protocol: "http", latency: 50, reason: "User visits app. Browser downloads main.js (small). HTTP/2 serves it alongside vendor.js in parallel." },
    { id: "c6", source: "http2-parallel", target: "runtime-loading", protocol: "internal", latency: 10, reason: "User navigates to dashboard. Runtime chunk loader checks cache: dashboard.1a2b.js cached? YES = instant. NO = fetch from CDN." },
    { id: "c7", source: "route-chunks", target: "runtime-loading", protocol: "http", latency: 100, reason: "Cache miss: dashboard chunk downloads. Suspense shows skeleton. Chunk executes, component renders, Suspense resolved." },
];

export function getCodeSplittingModuleConfig(): ModuleConfig {
    return {
        moduleId: "code-splitting",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_split",
                protocol: "internal",
                label: "Build + Split",
                payload: "vite build --mode production",
                sourceNodeId: "source-code",
                targetNodeId: "bundler",
                currentNodeId: "source-code",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "You deploy a new version that only changes the Dashboard component. With code splitting, what do users re-download?",
                options: [
                    { label: "The entire application bundle — any change invalidates all caches", isCorrect: false },
                    { label: "Only dashboard.newHash.js — vendor.js and other route chunks keep their old hashes and stay cached", isCorrect: true },
                    { label: "Nothing — service workers cache everything", isCorrect: false },
                    { label: "The vendor chunk and the dashboard chunk", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "Content-based hashing means only CHANGED chunks get new filenames. vendor.js: React did not change, same hash, browser serves from cache. main.js: routing config unchanged, same hash, cached. dashboard.js: Dashboard code changed, NEW hash, browser downloads the updated chunk. Users re-download only ~50KB instead of 4MB. This is the compounding benefit of code splitting + content hashing.",
                connectionId: "c4",
                nodeId: "route-chunks",
            },
        ],
        learningStory: {
            title: "The Modular Furniture Delivery",
            content: "Code splitting is like furniture delivered in separate boxes instead of one enormous crate. One giant crate is hard to ship, hard to handle, and if one item is damaged the whole delivery fails. Separate boxes can be shipped in parallel, handled independently, and replaced individually. If you order a replacement chair (deploy updated Dashboard), only the chair box ships again — not the entire bedroom set.",
            analogy: "A book with chapters in separate booklets. You subscribe to Chapter 1 (main.js — always needed) and download other chapters on demand as you read them. Chapter 3 (Dashboard) updated? You only receive the new Chapter 3 booklet — not the whole book reprinted.",
            lookFor: "Watch the Bundler split the monolith into THREE types of chunks: vendor (stable), app (small shell), and route chunks (on-demand). The HTTP/2 Parallel Download node shows multiple chunks loading simultaneously. The Runtime Loading node is the final piece — it orchestrates which chunks load and when at runtime!",
        },
    };
}
