import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "app-root",
        name: "App Root (Provider)",
        icon: "🌳",
        category: "client",
        runtime: "reactive",
        position: { x: 300, y: 60 },
        state: "idle",
        metadata: {},
        explanation: "The Context Provider wraps the component tree and makes a value available to ANY descendant — regardless of how deeply nested. createContext() creates the context object. The Provider's value prop is what consumers receive. When the value changes ALL consumers re-render — even if the component between them does not. This is both the power and the danger of Context.",
    },
    {
        id: "context-value",
        name: "Context Value",
        icon: "📡",
        category: "middleware",
        runtime: "reactive",
        position: { x: 100, y: 180 },
        state: "idle",
        metadata: {},
        explanation: "The context value is the data you want to share: { user, setUser, theme, toggleTheme }. The most important rule: do NOT create a new object on every render as the value prop — { user, setUser } creates a new object every render, causing ALL consumers to re-render even if user did not change. Fix: useMemo({ value: useMemo(() => ({ user, setUser }), [user]) }).",
    },
    {
        id: "layer-1",
        name: "Layout (No Props)",
        icon: "📐",
        category: "service",
        runtime: "reactive",
        position: { x: 300, y: 200 },
        state: "idle",
        metadata: {},
        explanation: "This component is between the Provider and the deep consumer. WITHOUT Context: it would have to receive user as a prop and pass it to its children who pass it to their children — this is prop drilling. WITH Context: this component does NOT need to know about user at all. It simply renders its children. Context skips layers entirely.",
    },
    {
        id: "layer-2",
        name: "Sidebar (No Props)",
        icon: "📋",
        category: "service",
        runtime: "reactive",
        position: { x: 300, y: 320 },
        state: "idle",
        metadata: {},
        explanation: "Another intermediate layer that does not need the user data but previously had to receive it as a prop just to pass it along. Context eliminates this boilerplate. However: if this component renders between the Provider and a consumer, and the context value changes, this component still re-renders. Context does not prevent intermediate re-renders — only memo can do that.",
    },
    {
        id: "consumer",
        name: "UserAvatar (Consumer)",
        icon: "👤",
        category: "client",
        runtime: "reactive",
        position: { x: 300, y: 440 },
        state: "idle",
        metadata: {},
        explanation: "The deep consumer calls useContext(UserContext) and receives the current value directly from the Provider — completely bypassing the 5 layers in between. No props needed. When the context value changes this consumer automatically re-renders with the new value. Multiple components can consume the same context and all update together.",
    },
    {
        id: "prop-drill",
        name: "Prop Drilling (Old Way)",
        icon: "😱",
        category: "middleware",
        runtime: "blocking",
        position: { x: 580, y: 240 },
        state: "idle",
        metadata: {},
        explanation: "Without Context you would pass user as a prop from App → Layout → Sidebar → Section → UserAvatar — 4 levels of unnecessary prop passing. Every intermediate component receives user just to forward it. This is prop drilling — it pollutes intermediate component interfaces with data they do not use and makes refactoring painful. Context eliminates this entirely.",
    },
    {
        id: "context-limit",
        name: "Context vs Redux",
        icon: "⚠️",
        category: "service",
        runtime: "event-loop",
        position: { x: 580, y: 380 },
        state: "idle",
        metadata: {},
        explanation: "Context is great for: theme, user auth, locale, UI state. Context is bad for: frequently changing data (every value change re-renders ALL consumers), complex state with many actions (use useReducer with Context or Redux). Rule of thumb: if more than 10 components consume the same context or the value changes more than a few times per second, consider Redux or Zustand instead.",
    },
];

const connections: Connection[] = [
    { id: "c1", source: "app-root", target: "context-value", protocol: "internal", latency: 5, reason: "Provider creates the context value. Whenever this value changes, React finds all consumers and schedules their re-render." },
    { id: "c2", source: "context-value", target: "layer-1", protocol: "internal", latency: 5, reason: "Context Provider wraps the tree. layout component renders without receiving user as a prop. Clean interface." },
    { id: "c3", source: "layer-1", target: "layer-2", protocol: "internal", latency: 5, reason: "Intermediate layers render their children normally. They know nothing about the user context — no prop passing needed." },
    { id: "c4", source: "layer-2", target: "consumer", protocol: "internal", latency: 5, reason: "Deep nested consumer component. No props from parent about user. Just renders its own UI." },
    { id: "c5", source: "consumer", target: "context-value", protocol: "internal", latency: 5, reason: "useContext(UserContext) — React traverses UP the component tree to find the nearest Provider and returns its current value. Direct access." },
    { id: "c6", source: "context-value", target: "prop-drill", protocol: "internal", latency: 5, reason: "OLD WAY: without context App passes user → Layout → Sidebar → Section → UserAvatar. 4 hops of meaningless prop forwarding." },
    { id: "c7", source: "context-value", target: "context-limit", protocol: "internal", latency: 5, reason: "Context performance warning: changing context value (e.g. cursor position updates 60fps) re-renders ALL consumers 60 times/sec. Only use for slow-changing shared state." },
];

export function getContextApiModuleConfig(): ModuleConfig {
    return {
        moduleId: "context-api",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_ctx",
                protocol: "internal",
                label: "Context Teleport",
                payload: "useContext(UserContext)",
                sourceNodeId: "consumer",
                targetNodeId: "context-value",
                currentNodeId: "consumer",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "Your ThemeContext value is { theme, setTheme } created inline in the Provider JSX. The user clicks a button and setTheme is called. What happens?",
                options: [
                    { label: "Only the ThemeToggle component re-renders", isCorrect: false },
                    { label: "ALL context consumers re-render — the inline object creates a new reference every render, even if theme did not change", isCorrect: true },
                    { label: "Nothing — context updates are batched", isCorrect: false },
                    { label: "Only components that use theme re-render", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "{ theme, setTheme } creates a new object on every render — React sees a new reference and re-renders ALL consumers even though theme is unchanged. Fix: const value = useMemo(() => ({ theme, setTheme }), [theme]) — now the object reference only changes when theme actually changes, preventing unnecessary consumer re-renders.",
                connectionId: "c1",
                nodeId: "context-value",
            },
        ],
        learningStory: {
            title: "The Radio Broadcast",
            content: "Context API is like a radio broadcast. The radio station (Provider) broadcasts a signal (context value). Any radio in the city (any consumer component) can tune in and receive the signal — regardless of which building they are in (component tree depth). The buildings in between do not need to carry the signal — it travels through the air directly to any radio that is tuned to the right frequency.",
            analogy: "A company-wide announcement system. The CEO (Provider) makes an announcement. Every employee (consumer) with a phone extension (useContext) hears it directly. The middle managers (intermediate components) do not need to relay the message — the PA system handles distribution.",
            lookFor: "Watch the packet SKIP layers 1 and 2 completely — it teleports from Consumer directly to Context Value! Compare with the Prop Drilling path (right side) where data must pass through every intermediate node. This is the entire value proposition of Context API visualized!",
        },
    };
}
