import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "browser",
        name: "Browser (View)",
        icon: "📱",
        category: "client",
        runtime: "reactive",
        position: { x: 100, y: 80 },
        state: "idle",
        metadata: {},
        explanation: "The View is everything the user sees and touches. In MERN the View is React — it renders HTML from component state and fires events when users interact. The View NEVER reads from the database directly — it only talks to the Controller via HTTP. Why: the browser has no database credentials and should not. Security principle: never expose your data layer to untrusted clients.",
    },
    {
        id: "controller",
        name: "Controller (Express)",
        icon: "🎛️",
        category: "service",
        runtime: "event-loop",
        position: { x: 500, y: 80 },
        state: "idle",
        metadata: {},
        explanation: "The Controller is the traffic cop. It receives HTTP requests from the View, validates input, applies business rules, calls the Model to get or change data, then sends a response back. In MERN the Controller is Express route handlers. It contains NO data access logic (that belongs in the Model) and NO rendering logic (that belongs in the View). Fat controllers are an anti-pattern.",
    },
    {
        id: "model",
        name: "Model (Mongoose)",
        icon: "🧩",
        category: "database",
        runtime: "blocking",
        position: { x: 100, y: 400 },
        state: "idle",
        metadata: {},
        explanation: "The Model is the data layer. In MERN the Model is Mongoose schemas and methods — they define the shape of data, run validations before saves, and provide methods like User.findByEmail(). The Model talks only to MongoDB. It knows NOTHING about HTTP, rendering, or routing. Keeping Models thin and focused makes them reusable and testable in isolation.",
    },
    {
        id: "mongodb",
        name: "MongoDB",
        icon: "🍃",
        category: "database",
        runtime: "blocking",
        position: { x: 500, y: 400 },
        state: "idle",
        metadata: {},
        explanation: "MongoDB is the persistent storage layer. It receives BSON commands from Mongoose (the Model) and returns documents. It has no concept of HTTP, views, or controllers — it just stores and retrieves data. In a clean MVC architecture nothing except the Model ever touches the database directly.",
    },
    {
        id: "response",
        name: "JSON Response",
        icon: "📊",
        category: "service",
        runtime: "event-loop",
        position: { x: 300, y: 240 },
        state: "idle",
        metadata: {},
        explanation: "The Controller assembles data from the Model and sends a JSON response back to the View. This is the return journey: MongoDB → Model → Controller → View. The View receives JSON and re-renders the relevant components. The response contains only what the View needs — never raw database documents with all fields.",
    },
];

const connections: Connection[] = [
    {
        id: "c1",
        source: "browser",
        target: "controller",
        protocol: "http",
        latency: 15,
        reason: "User action (click, form submit) sends HTTP request to Express. The View speaks only to the Controller — never to the Model or MongoDB directly.",
    },
    {
        id: "c2",
        source: "controller",
        target: "model",
        protocol: "internal",
        latency: 5,
        reason: "Controller calls Model methods: User.findById(id), Post.create(data). The Model handles all database interaction — Controller stays thin.",
    },
    {
        id: "c3",
        source: "model",
        target: "mongodb",
        protocol: "db-query",
        latency: 25,
        reason: "Mongoose serializes the query to BSON and sends to MongoDB. Index lookups, document reads, writes — all handled by the storage engine.",
    },
    {
        id: "c4",
        source: "mongodb",
        target: "model",
        protocol: "db-query",
        latency: 25,
        reason: "MongoDB returns BSON documents. Mongoose deserializes to JavaScript objects, runs any virtuals or transforms, returns to Controller.",
    },
    {
        id: "c5",
        source: "model",
        target: "response",
        protocol: "internal",
        latency: 5,
        reason: "Model returns data to Controller. Controller shapes it (pick only needed fields, add pagination meta) and calls res.json().",
    },
    {
        id: "c6",
        source: "response",
        target: "browser",
        protocol: "http",
        latency: 15,
        reason: "JSON response travels back to React. React updates component state, triggers re-render. View shows the new data. One full MVC cycle complete.",
    },
];

export function getMvcModuleConfig(): ModuleConfig {
    return {
        moduleId: "mvc",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_mvc",
                protocol: "http",
                label: "GET /api/posts",
                payload: "User clicks Posts tab",
                sourceNodeId: "browser",
                targetNodeId: "controller",
                currentNodeId: "browser",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "A junior developer puts a MongoDB query directly inside a React component using fetch('/db/users'). What is wrong?",
                options: [
                    { label: "Nothing wrong — it works if CORS is configured", isCorrect: false },
                    { label: "The React component (View) is bypassing the Controller and Model — this exposes DB credentials, skips validation, and violates separation of concerns", isCorrect: true },
                    { label: "MongoDB does not support HTTP", isCorrect: false },
                    { label: "React cannot handle async operations", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "MVC exists for security and maintainability. If Views talk directly to databases: (1) DB credentials must be in the frontend code (exposed to anyone), (2) no authentication or authorization checks, (3) business rules are scattered everywhere. The Controller layer is the security checkpoint — every data access goes through it.",
                connectionId: "c1",
                nodeId: "controller",
            },
        ],
        learningStory: {
            title: "The Restaurant Kitchen",
            content: "MVC is how every restaurant works. You (the user) only interact with the waiter (Controller). The waiter takes your order, goes to the kitchen (Model), which prepares the food using ingredients from the pantry (MongoDB). You never walk into the kitchen — that would be chaos. The waiter brings your food (JSON response) back to your table (View). Clean separation, everyone knows their job.",
            analogy: "You order pizza (HTTP request). The waiter (Controller) writes it down and gives it to the chef (Model). The chef gets ingredients from the fridge (MongoDB). The waiter brings the pizza back to you (response). You never open the fridge yourself.",
            lookFor: "Watch the triangular flow! Browser → Controller → Model → MongoDB → Model → Controller → Browser. Notice the response goes through the center node — the Controller always mediates. The View and the Database NEVER communicate directly!",
        },
    };
}
