import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "user-action",
        name: "User Interaction",
        icon: "👆",
        category: "client",
        runtime: "reactive",
        position: { x: 60, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "User actions create two types of state needs: UI state (is this dropdown open? is this modal showing?) and Server state (what posts does this user have? what is their profile?). These require completely different management strategies. Mixing them in the same useState leads to over-fetching, stale data, and complex synchronization code.",
    },
    {
        id: "ui-state",
        name: "UI State (Local)",
        icon: "🎨",
        category: "service",
        runtime: "reactive",
        position: { x: 280, y: 100 },
        state: "idle",
        metadata: {},
        explanation: "UI State is CLIENT-ONLY state that has no server representation. Examples: isModalOpen, activeTab, isDropdownOpen, formInputValue, isLoading (spinner visible), selectedItems. This state lives and dies with the component. When the user refreshes the page, UI state resets — and that is correct behavior. Manage with useState or useReducer. No need for server sync.",
    },
    {
        id: "server-state",
        name: "Server State (Remote)",
        icon: "☁️",
        category: "service",
        runtime: "event-loop",
        position: { x: 280, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "Server State is data that LIVES on the server and is only CACHED in the client. Examples: user profile, list of posts, search results, order history. This data can change on the server without your component knowing. It can become stale. Multiple components might need the same server data. It needs loading and error states. It needs cache invalidation. This is complex — do not manage it with plain useState.",
    },
    {
        id: "react-query",
        name: "React Query / SWR",
        icon: "🔄",
        category: "middleware",
        runtime: "event-loop",
        position: { x: 500, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "React Query (TanStack Query) and SWR are server state management libraries. They handle: automatic background refetching, cache deduplication (10 components requesting the same user profile = 1 network request), stale-while-revalidate (show cached data immediately, update in background), automatic retry on failure, cache invalidation after mutations, optimistic updates. Use these instead of useEffect + useState for all server data.",
    },
    {
        id: "cache",
        name: "Client Cache",
        icon: "⚡",
        category: "database",
        runtime: "event-loop",
        position: { x: 700, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "React Query maintains a cache keyed by query key: ['user', userId]. When Component A and Component B both need the same user, only ONE network request is made. Both receive data from the cache. Cache entries have a staleTime (how long before considered stale) and cacheTime (how long before garbage collected). On window focus: React Query automatically refetches stale data.",
    },
    {
        id: "api-server",
        name: "API Server",
        icon: "⚡",
        category: "service",
        runtime: "event-loop",
        position: { x: 700, y: 200 },
        state: "idle",
        metadata: {},
        explanation: "The actual data source. React Query fetches from the API and caches the response. After a mutation (POST /posts), React Query invalidates the posts cache — the next render of any component using that query triggers a fresh fetch. This ensures server state stays synchronized without manual cache management.",
    },
    {
        id: "zustand-local",
        name: "Zustand (UI State)",
        icon: "🏪",
        category: "service",
        runtime: "reactive",
        position: { x: 500, y: 100 },
        state: "idle",
        metadata: {},
        explanation: "For UI state that needs to be shared across components (sidebar open state, active theme, selected table rows), use a lightweight store like Zustand or Context. Keep it completely separate from server state. The golden rule: never put server-fetched data (user profile, posts) in your Zustand store. Use React Query for server state, Zustand for shared UI state.",
    },
];

const connections: Connection[] = [
    { id: "c1", source: "user-action", target: "ui-state", protocol: "internal", latency: 5, reason: "User clicks dropdown → isOpen=true. Local UI state update. Instant, no network, no server sync needed." },
    { id: "c2", source: "user-action", target: "server-state", protocol: "internal", latency: 5, reason: "User clicks Load More Posts → need server data. React Query checks cache first." },
    { id: "c3", source: "ui-state", target: "zustand-local", protocol: "internal", latency: 5, reason: "Shared UI state (sidebar open) goes to Zustand. Component-local UI state stays in useState. Never in server state." },
    { id: "c4", source: "server-state", target: "react-query", protocol: "internal", latency: 5, reason: "React Query intercepts: is this query cached? Is it fresh? If yes return cache. If no or stale, fetch from API." },
    { id: "c5", source: "react-query", target: "cache", protocol: "internal", latency: 5, reason: "Cache hit: data returned immediately. Cache miss or stale: fetch starts, loading state shown, data returned when available." },
    { id: "c6", source: "react-query", target: "api-server", protocol: "http", latency: 100, reason: "Network request to API. Response cached under query key. All components using this key receive the update." },
    { id: "c7", source: "cache", target: "user-action", protocol: "internal", latency: 5, reason: "Stale-while-revalidate: cached data shown immediately (fast), background fetch updates it. User sees data with no loading spinner." },
];

export function getServerUiStateModuleConfig(): ModuleConfig {
    return {
        moduleId: "server-ui-state",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_state",
                protocol: "internal",
                label: "Data Request",
                payload: "useQuery(['posts', userId])",
                sourceNodeId: "user-action",
                targetNodeId: "server-state",
                currentNodeId: "user-action",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "You store fetched user data in useState and useEffect. User opens the app on two tabs. Tab 1 updates the username. What happens in Tab 2?",
                options: [
                    { label: "Tab 2 automatically updates — React syncs state", isCorrect: false },
                    { label: "Tab 2 shows stale data — useState is local to that tab. React Query with window focus refetch would auto-update Tab 2", isCorrect: true },
                    { label: "An error is thrown", isCorrect: false },
                    { label: "The server rejects the update", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "useState is local to the browser tab — it has no awareness of server changes. With React Query's refetchOnWindowFocus: true (the default), switching to Tab 2 triggers a background refetch and shows the updated username automatically. This is the stale-while-revalidate pattern: show cached data, verify it is still fresh in the background.",
                connectionId: "c5",
                nodeId: "react-query",
            },
        ],
        learningStory: {
            title: "The Newspaper vs the Whiteboard",
            content: "UI State is a whiteboard — temporary notes for the current session. Sidebar open? Write it on the whiteboard. Modal showing? Whiteboard. Nobody else sees it, it erases when you leave. Server State is a newspaper — the content lives at the publisher and your app holds a copy. The copy can become stale. React Query is the newspaper subscription service: it keeps your copy updated automatically and alerts you when there is new content.",
            analogy: "A hotel room vs the hotel restaurant menu. Room temperature (UI state) — local to your room, nobody else cares. Today's menu (server state) — the kitchen determines it, you have a copy, it changes at lunch and dinner and your copy can become stale. You need a system to refresh your copy automatically.",
            lookFor: "The two parallel paths diverge from User Action — UI State goes left (instant, local), Server State goes right (cached, async). Watch React Query check the Cache before hitting the API Server. Cache hit = instant response. Cache miss = network request. This split is the entire concept of Server vs UI State!",
        },
    };
}
