import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "mount-trigger",
        name: "Component Mounts",
        icon: "🌱",
        category: "client",
        runtime: "reactive",
        position: { x: 60, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "Mount: the component appears in the DOM for the first time. In function components this means the function ran for the first time and React committed its output to the real DOM. In class components this was componentDidMount. Mounting is expensive — React creates DOM nodes, measures layout, and runs all mount effects. Components mount when: parent renders them for the first time, router navigates to a new route, a condition becomes true (conditional rendering).",
    },
    {
        id: "initial-render",
        name: "Initial Render",
        icon: "🎨",
        category: "service",
        runtime: "reactive",
        position: { x: 240, y: 120 },
        state: "idle",
        metadata: {},
        explanation: "The component function runs for the first time. useState initializers run. The JSX is converted to React elements (Virtual DOM). This is a PURE operation — no side effects, no data fetching, no DOM access. React compares this output against an empty previous tree and schedules all DOM insertions. The real DOM does not exist yet during this phase.",
    },
    {
        id: "dom-commit",
        name: "DOM Commit (Mount)",
        icon: "🌲",
        category: "service",
        runtime: "blocking",
        position: { x: 440, y: 120 },
        state: "idle",
        metadata: {},
        explanation: "React commits the initial render to the real DOM — creates HTML elements, sets attributes, attaches event listeners. This is synchronous and fast. After this line, the component is visible to the user. useLayoutEffect fires here (synchronously). Then the browser paints — user sees the component for the first time.",
    },
    {
        id: "use-effect-mount",
        name: "useEffect (Mount)",
        icon: "🔮",
        category: "middleware",
        runtime: "event-loop",
        position: { x: 640, y: 120 },
        state: "idle",
        metadata: {},
        explanation: "After the browser paints, useEffect with [] dependency runs. This is where you: fetch initial data (call the API), set up subscriptions (WebSocket.listen()), start timers (setInterval). Why AFTER paint: useEffect does not block the browser from showing the component to the user. The user sees the UI immediately, then data loads asynchronously.",
    },
    {
        id: "update-trigger",
        name: "Update Trigger",
        icon: "⚡",
        category: "client",
        runtime: "reactive",
        position: { x: 240, y: 350 },
        state: "idle",
        metadata: {},
        explanation: "Something changed: useState setter called, context value changed, parent re-rendered. React schedules a re-render. This can happen thousands of times during a component's life. Each update is cheap — React diffs the new output against the previous and only applies the minimum DOM changes. Triggers: user interactions, API responses, timers, parent re-renders.",
    },
    {
        id: "re-render",
        name: "Re-render + Diff",
        icon: "🔄",
        category: "service",
        runtime: "reactive",
        position: { x: 440, y: 350 },
        state: "idle",
        metadata: {},
        explanation: "Component function runs again with new state/props. React elements are created again. The diffing algorithm compares new VDOM against the previous VDOM. Only the changed DOM nodes are updated — not the whole component. useEffect cleanup runs (from the previous render) then the new useEffect runs if dependencies changed.",
    },
    {
        id: "unmount",
        name: "Component Unmounts",
        icon: "💀",
        category: "client",
        runtime: "reactive",
        position: { x: 640, y: 350 },
        state: "idle",
        metadata: {},
        explanation: "The component is removed from the DOM. Reasons: conditional rendering (if statement becomes false), route navigation away, parent unmounts. React calls all useEffect cleanup functions in reverse order — this is critical for avoiding memory leaks: cancel fetch requests, clear setInterval, remove event listeners, close WebSocket connections. Failing to clean up is the #1 cause of React memory leaks.",
    },
    {
        id: "cleanup",
        name: "useEffect Cleanup",
        icon: "🧹",
        category: "middleware",
        runtime: "event-loop",
        position: { x: 840, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "The cleanup function returned from useEffect is called: (1) before the component unmounts — final cleanup, (2) before the next useEffect runs when dependencies change — prevents stale subscriptions. Pattern: useEffect(() => { const sub = subscribe(); return () => sub.unsubscribe(); }, [channel]). If channel changes: old subscription cleaned up, new one created.",
    },
];

const connections: Connection[] = [
    { id: "c1", source: "mount-trigger", target: "initial-render", protocol: "internal", latency: 5, reason: "First render: component function executes, useState initializers run, JSX returned as React elements. Pure — no side effects." },
    { id: "c2", source: "initial-render", target: "dom-commit", protocol: "internal", latency: 5, reason: "React commits initial output to DOM: createElement, appendChild, setAttribute. Component becomes visible. useLayoutEffect fires synchronously here." },
    { id: "c3", source: "dom-commit", target: "use-effect-mount", protocol: "internal", latency: 10, reason: "Browser paints. Then useEffect([]) fires: API calls, subscriptions, timers. Non-blocking — user already sees the component." },
    { id: "c4", source: "update-trigger", target: "re-render", protocol: "internal", latency: 5, reason: "State or props changed. Component function runs again. Diffing determines minimum DOM changes needed." },
    { id: "c5", source: "re-render", target: "use-effect-mount", protocol: "internal", latency: 5, reason: "If useEffect dependencies changed: cleanup from previous run, then new effect runs. If deps unchanged: effect skipped." },
    { id: "c6", source: "unmount", target: "cleanup", protocol: "internal", latency: 5, reason: "Component removed from DOM. ALL useEffect cleanups run: cancel requests, clear timers, remove listeners. Memory freed." },
    { id: "c7", source: "cleanup", target: "mount-trigger", protocol: "internal", latency: 20, reason: "After unmount, the same component type may remount elsewhere (route re-navigation). Full lifecycle starts again from scratch." },
];

export function getComponentLifecycleModuleConfig(): ModuleConfig {
    return {
        moduleId: "component-lifecycle",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_life",
                protocol: "internal",
                label: "Lifecycle Flow",
                payload: "<UserProfile userId={123} />",
                sourceNodeId: "mount-trigger",
                targetNodeId: "initial-render",
                currentNodeId: "mount-trigger",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "useEffect(() => { const id = setInterval(poll, 1000); }, []) — user navigates away. What happens?",
                options: [
                    { label: "The interval stops automatically when the component unmounts", isCorrect: false },
                    { label: "Memory leak: the interval keeps running forever, calling poll() and potentially updating unmounted component state", isCorrect: true },
                    { label: "React throws an error", isCorrect: false },
                    { label: "The interval pauses and resumes when the user comes back", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "setInterval survives component unmounting — it runs on the browser's timer thread, not React's lifecycle. Without cleanup: the interval fires every second, poll() runs, tries to setState on an unmounted component (React warning), and the garbage collector cannot free the component because the interval holds a reference to it. Fix: return () => clearInterval(id) from the useEffect.",
                connectionId: "c6",
                nodeId: "unmount",
            },
        ],
        learningStory: {
            title: "The Life of a TV Show Character",
            content: "A React component has a lifecycle just like a TV show character. They are introduced (Mount) — the writers set up their backstory. They evolve through episodes (Updates) — things happen, they change. Then they exit the show (Unmount) — loose ends are tied up (cleanup). A bad showrunner forgets to resolve the character's subplots when they leave — that is a memory leak.",
            analogy: "Moving into an apartment (Mount): you turn on the heating, subscribe to internet, get a key cut. Living there (Updates): things change, you adjust. Moving out (Unmount): you turn off the heating, cancel the internet, return the key. The cleanup is just as important as the setup.",
            lookFor: "Follow the lifecycle from left to right: Mount → Initial Render → DOM Commit → useEffect(Mount). Then watch the Update cycle loop (re-renders). Finally see the Unmount → Cleanup path. The cleanup node is critical — it is where memory leaks are prevented!",
        },
    };
}
