import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "initial-load",
        name: "App Initial Load",
        icon: "🚀",
        category: "client",
        runtime: "reactive",
        position: { x: 60, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "User visits your app for the first time. Without lazy loading: the browser downloads the ENTIRE JavaScript bundle — including Dashboard, Settings, AdminPanel, Charts library, PDF generator — even though the user only sees the Login page. A 4MB bundle takes 8 seconds on a slow 3G connection. First Contentful Paint is delayed. The user stares at a blank screen.",
    },
    {
        id: "eager-bundle",
        name: "Eager Bundle (4MB)",
        icon: "📦",
        category: "service",
        runtime: "blocking",
        position: { x: 280, y: 100 },
        state: "idle",
        metadata: {},
        explanation: "Eager loading: ALL code bundled into one file. Every route's component, every library, every utility — downloaded upfront. Fast subsequent navigation (everything is in memory). Terrible initial load time. The user on the Login page downloaded the PDF generator they will never use. For simple apps this is fine. For complex apps with many routes, this kills performance.",
    },
    {
        id: "lazy-import",
        name: "React.lazy + Suspense",
        icon: "🐌",
        category: "middleware",
        runtime: "event-loop",
        position: { x: 280, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "React.lazy(() => import('./Dashboard')) creates a lazy component. When the route renders for the first time, the import() call triggers a dynamic import — a separate network request for just the Dashboard chunk. Suspense provides a fallback (spinner) while the chunk loads. If the user never visits Dashboard, its code is never downloaded.",
    },
    {
        id: "route-chunk",
        name: "Route Chunk Download",
        icon: "📥",
        category: "service",
        runtime: "event-loop",
        position: { x: 500, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "Vite/Webpack splits each lazy-imported component into a separate .js file (chunk). The Dashboard chunk might be 200KB. The PDFGenerator chunk might be 800KB. These are only downloaded when the user navigates to that route. The initial bundle might shrink from 4MB to 200KB — 20x faster first load. Each subsequent route navigation downloads only its chunk.",
    },
    {
        id: "suspense",
        name: "Suspense Fallback",
        icon: "⏳",
        category: "service",
        runtime: "reactive",
        position: { x: 500, y: 100 },
        state: "idle",
        metadata: {},
        explanation: "While a lazy chunk is downloading, Suspense renders the fallback: a spinner, skeleton screen, or minimal placeholder. The rest of the app remains interactive. Suspense boundaries can be nested: a route-level Suspense shows a page skeleton, a component-level Suspense shows a section spinner. Without Suspense, React.lazy throws an error.",
    },
    {
        id: "prefetch",
        name: "Prefetch Hints",
        icon: "🔮",
        category: "middleware",
        runtime: "event-loop",
        position: { x: 700, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "Advanced optimization: prefetch chunks the user will likely need next. When hovering over a navigation link, preload that route's chunk: import(/* webpackPrefetch: true */ './Dashboard'). The browser downloads it during idle time — when the user actually clicks, the chunk is already cached. Combines lazy loading benefits (small initial bundle) with eager loading benefits (instant navigation incumbents).",
    },
    {
        id: "cached-chunk",
        name: "Cached in Browser",
        icon: "⚡",
        category: "database",
        runtime: "event-loop",
        position: { x: 700, y: 380 },
        state: "idle",
        metadata: {},
        explanation: "Downloaded chunks are cached by the browser. A user visiting the Dashboard twice only downloads the chunk once — subsequent visits are instant. Content-hashed filenames (dashboard.abc123.js) enable long-term caching: if the chunk has not changed, the hash stays the same and the browser serves it from cache for months. Only changed chunks get new hashes and are re-downloaded.",
    },
];

const connections: Connection[] = [
    { id: "c1", source: "initial-load", target: "eager-bundle", protocol: "http", latency: 200, reason: "WITHOUT lazy loading: entire 4MB bundle downloads before any JS executes. 8 seconds on 3G. Blank screen for user." },
    { id: "c2", source: "initial-load", target: "lazy-import", protocol: "http", latency: 50, reason: "WITH lazy loading: only the 200KB initial bundle downloads. Login page renders in 1 second. Remaining routes loaded on demand." },
    { id: "c3", source: "lazy-import", target: "route-chunk", protocol: "http", latency: 100, reason: "User navigates to Dashboard. React.lazy triggers import('./Dashboard'). 200KB chunk downloads. Only happens once." },
    { id: "c4", source: "lazy-import", target: "suspense", protocol: "internal", latency: 5, reason: "While chunk downloads Suspense shows a skeleton screen. App remains interactive — user can still click other things." },
    { id: "c5", source: "route-chunk", target: "prefetch", protocol: "internal", latency: 5, reason: "Dashboard loaded. Prefetch hints: on hover over Settings link, start downloading the Settings chunk in the background." },
    { id: "c6", source: "prefetch", target: "cached-chunk", protocol: "http", latency: 50, reason: "Settings chunk prefetched during idle time. When user clicks Settings link: chunk is already in browser cache. Instant navigation." },
    { id: "c7", source: "cached-chunk", target: "initial-load", protocol: "internal", latency: 5, reason: "Next app visit: all previously downloaded chunks served from browser cache. App feels instant from second load onwards." },
];

export function getLazyLoadingModuleConfig(): ModuleConfig {
    return {
        moduleId: "lazy-loading",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_lazy",
                protocol: "http",
                label: "Route Navigation",
                payload: "User navigates to /dashboard",
                sourceNodeId: "initial-load",
                targetNodeId: "lazy-import",
                currentNodeId: "initial-load",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "Your React app imports Chart.js, PDF.js, and a rich text editor at the top of App.tsx even though only 10% of users access those features. What is the impact?",
                options: [
                    { label: "No impact — modern bundlers tree-shake unused imports", isCorrect: false },
                    { label: "All users download those libraries on the initial page load — adding ~2MB to the initial bundle even for users who never use those features", isCorrect: true },
                    { label: "The browser caches libraries so it does not matter", isCorrect: false },
                    { label: "Only the used functions are included by tree-shaking", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "Tree-shaking removes UNUSED functions but if you import the library it IS used (even if rarely). Chart.js = 200KB, PDF.js = 800KB, rich text editor = 500KB. Every user pays this cost upfront. Fix: const Chart = React.lazy(() => import('./ChartWrapper')). Only the 10% who visit the charts page download Chart.js. 90% of users save 200KB.",
                connectionId: "c3",
                nodeId: "route-chunk",
            },
        ],
        learningStory: {
            title: "The On-Demand Video Streaming",
            content: "Lazy loading is like Netflix vs buying DVDs. Buying all DVDs upfront (eager loading) means you have everything immediately but you paid for 500 movies you never watch. Netflix (lazy loading) only streams the movie you actually want to watch right now. The others are available on demand but you do not pay the cost until you need them. Prefetching is like Netflix auto-downloading the next episode while you watch the current one.",
            analogy: "A restaurant menu vs a buffet. Buffet (eager loading): all dishes prepared upfront, available instantly, but the kitchen cooked food nobody will eat. Menu (lazy loading): only prepare dishes that customers order. Takes a moment to prepare (chunk download) but no wasted preparation for dishes nobody wants.",
            lookFor: "Compare the Eager Bundle (top) taking 200ms to download 4MB vs the Lazy Import (bottom) taking 50ms for 200KB. Then watch the Route Chunk only download when needed. Finally see Prefetch downloading the next chunk BEFORE the user even asks for it — background preparation for instant future navigation!",
        },
    };
}
