import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "store",
        name: "Zustand Store",
        icon: "🏪",
        category: "service",
        runtime: "reactive",
        position: { x: 400, y: 60 },
        state: "idle",
        metadata: {},
        explanation: "The global store is a single JavaScript object outside the React component tree. Zustand uses closures and subscriptions. Redux uses a single immutable state tree with reducers. Both solve the same problem: sharing state between components that are NOT in a parent-child relationship. The store is the single source of truth for global data: current user, auth token, shopping cart, notification count.",
    },
    {
        id: "cart-component",
        name: "Cart Icon (Header)",
        icon: "🛒",
        category: "client",
        runtime: "reactive",
        position: { x: 100, y: 200 },
        state: "idle",
        metadata: {},
        explanation: "The cart icon in the header displays the number of items in the cart. It subscribes to the cart state in the global store. When ANY component adds an item to the cart (even a component on a completely different page), this icon automatically updates. No prop drilling — it accesses the store directly with useCartStore(state => state.items.length).",
    },
    {
        id: "product-page",
        name: "Product Page",
        icon: "📦",
        category: "client",
        runtime: "reactive",
        position: { x: 400, y: 200 },
        state: "idle",
        metadata: {},
        explanation: "The Product Page has an Add to Cart button. When clicked it dispatches an action to the global store: addItem(product). It does NOT pass the item up to a parent or through props. It writes directly to the global store. The store updates, ALL subscribers (CartIcon, CartDrawer, CheckoutPage) automatically re-render with the new state. No component communication needed.",
    },
    {
        id: "checkout",
        name: "Checkout Page",
        icon: "💳",
        category: "client",
        runtime: "reactive",
        position: { x: 700, y: 200 },
        state: "idle",
        metadata: {},
        explanation: "The Checkout page reads the full cart from the global store to display the order summary. Even though CartPage and ProductPage are completely different routes (different component trees), they share the same cart state through the global store. Without global state, you would need to lift cart state to the router level and prop-drill it through every route.",
    },
    {
        id: "selector",
        name: "Selector (Derived State)",
        icon: "🔍",
        category: "middleware",
        runtime: "reactive",
        position: { x: 400, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "Selectors compute derived state from the store without modifying it. Examples: totalPrice = items.reduce(sum + item.price), itemCount = items.length, isCartEmpty = items.length === 0. In Zustand: useStore(state => state.items.length). In Redux: createSelector from reselect. Selectors memoize — they only recompute when their input (cart items) changes, preventing unnecessary re-renders.",
    },
    {
        id: "action",
        name: "Action / Mutation",
        icon: "⚡",
        category: "service",
        runtime: "event-loop",
        position: { x: 700, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "Actions (Redux) or mutations (Zustand) are the ONLY way to update global state. This unidirectionality makes state changes predictable and debuggable. Redux: dispatch({ type: ADD_TO_CART, payload: product }) → reducer creates new state. Zustand: set(state => ({ items: [...state.items, product] })). Redux DevTools lets you time-travel through every action — invaluable for debugging.",
    },
    {
        id: "persist",
        name: "State Persistence",
        icon: "💾",
        category: "database",
        runtime: "blocking",
        position: { x: 100, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "Global state can be persisted to localStorage (redux-persist, zustand/middleware persist). When the user closes the browser and returns, the cart is still full. Why not just use localStorage directly: global state provides reactive updates (components re-render when state changes), whereas localStorage is not reactive (reading it does not trigger re-renders). Persist middleware bridges both.",
    },
];

const connections: Connection[] = [
    { id: "c1", source: "product-page", target: "action", protocol: "internal", latency: 5, reason: "User clicks Add to Cart. ProductPage calls the store's addItem action with the product data. No parent components involved." },
    { id: "c2", source: "action", target: "store", protocol: "internal", latency: 5, reason: "Action updates the store: new immutable state created with the added item. All subscribers notified synchronously." },
    { id: "c3", source: "store", target: "cart-component", protocol: "internal", latency: 5, reason: "CartIcon selector (state => state.items.length) detects change. CartIcon re-renders with new count: 3 → 4." },
    { id: "c4", source: "store", target: "checkout", protocol: "internal", latency: 5, reason: "CheckoutPage selector (state => state.items) detects change. Checkout updates its order summary automatically." },
    { id: "c5", source: "store", target: "selector", protocol: "internal", latency: 5, reason: "Selectors recompute derived values: totalPrice=$147, itemCount=4, isCartEmpty=false. Only recomputes when cart items change." },
    { id: "c6", source: "selector", target: "persist", protocol: "internal", latency: 10, reason: "Persist middleware detects state change. Serializes cart to JSON. Writes to localStorage. Cart survives page refresh." },
    { id: "c7", source: "persist", target: "store", protocol: "internal", latency: 5, reason: "On page load: persist middleware reads localStorage, hydrates the store with the saved cart. User returns to find their cart intact." },
];

export function getGlobalStateModuleConfig(): ModuleConfig {
    return {
        moduleId: "global-state",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_store",
                protocol: "internal",
                label: "Add to Cart",
                payload: 'useCartStore.getState().addItem(product)',
                sourceNodeId: "product-page",
                targetNodeId: "action",
                currentNodeId: "product-page",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "When should you use global state vs local state vs Context API?",
                options: [
                    { label: "Always use global state for everything", isCorrect: false },
                    { label: "Local state: one component. Context: slow-changing shared state (theme, user). Global state (Zustand/Redux): frequently-updated shared state (cart, notifications) or complex state with many actions", isCorrect: true },
                    { label: "Only use global state in large apps", isCorrect: false },
                    { label: "Context is always better than Redux", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "State placement rule: as local as possible, as global as necessary. useState for single-component state. useContext for slow-changing data shared across many components (theme, auth). Zustand/Redux for: cart that multiple pages share, real-time notifications, complex state with many action types, or state that needs time-travel debugging. Over-globalizing state causes unnecessary re-renders everywhere.",
                connectionId: "c2",
                nodeId: "store",
            },
        ],
        learningStory: {
            title: "The City Power Grid",
            content: "Global state is like a city power grid. Local state is a house battery — useful for just that house. Context is a neighborhood transformer — serves a local area. Global state is the main power grid — any building in the city can plug in and get power. When the power company (store) updates voltage (state), every connected building (component) immediately notices.",
            analogy: "A stock market ticker. No matter which floor of a building you are on, the ticker shows the same real-time stock price. The stock price (global state) is not passed from floor to floor (prop drilling) — every ticker is connected directly to the exchange (store) and updates simultaneously.",
            lookFor: "Watch THREE different components (Cart Icon, Product Page, Checkout) all connect to the central Store node. When the Action updates the Store all three update simultaneously — no prop passing, no parent coordination. This is the power of global state!",
        },
    };
}
