import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "parent-render",
        name: "Parent Re-renders",
        icon: "🔄",
        category: "client",
        runtime: "reactive",
        position: { x: 60, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "The parent component re-renders (state changed, context updated, parent's parent re-rendered). By default in React ALL children re-render regardless of whether their props changed. A parent with 10 children that re-renders 100 times = 1000 component function calls, even if 9 of those children receive identical props. This is the problem memoization solves.",
    },
    {
        id: "without-memo",
        name: "Without React.memo",
        icon: "🐌",
        category: "service",
        runtime: "reactive",
        position: { x: 280, y: 100 },
        state: "idle",
        metadata: {},
        explanation: "WITHOUT React.memo: parent re-renders → ALL children re-render, even if props are identical. A heavy Chart component receiving the same data prop re-renders and recalculates the entire chart layout on every parent keystroke. Even 'pure' function components re-render by default — they are just function calls that React makes again. No automatic optimization.",
    },
    {
        id: "with-memo",
        name: "React.memo (Wrapped)",
        icon: "🚀",
        category: "service",
        runtime: "reactive",
        position: { x: 280, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "WITH React.memo: parent re-renders → React performs a SHALLOW COMPARISON of previous and current props. If all props are shallowly equal (same primitive values, same object references), React SKIPS the child render entirely and reuses the previous output. The child function is never called. For expensive components (charts, tables, complex forms) this is a massive performance win.",
    },
    {
        id: "use-callback",
        name: "useCallback",
        icon: "🎯",
        category: "middleware",
        runtime: "reactive",
        position: { x: 500, y: 100 },
        state: "idle",
        metadata: {},
        explanation: "useCallback memoizes a FUNCTION reference. Without it: <Child onClick={() => doSomething()} /> creates a NEW function on every parent render. React.memo sees a new prop reference → bails out optimization, re-renders Child anyway. With useCallback: const handler = useCallback(() => doSomething(), []) — same function reference across renders. React.memo's shallow comparison now works correctly.",
    },
    {
        id: "use-memo",
        name: "useMemo",
        icon: "🔢",
        category: "middleware",
        runtime: "reactive",
        position: { x: 500, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "useMemo memoizes a COMPUTED VALUE. Expensive calculation: const sorted = useMemo(() => items.sort(compareByDate), [items]). Without useMemo: sort runs on EVERY render even when items has not changed. With useMemo: sort only runs when items changes. Use for: expensive array operations (filter/sort/reduce on large arrays), complex object construction passed as props, derived data computations.",
    },
    {
        id: "bail-out",
        name: "Render Bail-out",
        icon: "⏭️",
        category: "service",
        runtime: "reactive",
        position: { x: 720, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "When React.memo determines props are shallowly equal (unchanged), it returns the PREVIOUS render output without calling the component function. The child is skipped entirely in the render phase. This is called a bail-out. Note: bail-out only works if you also use useCallback for function props and useMemo for object/array props — otherwise new references defeat the memo check.",
    },
    {
        id: "cost-warning",
        name: "Memoization Cost",
        icon: "⚠️",
        category: "middleware",
        runtime: "reactive",
        position: { x: 720, y: 380 },
        state: "idle",
        metadata: {},
        explanation: "Memoization is NOT free. Every React.memo comparison has a cost: React must compare ALL props shallowly on every render. Every useMemo/useCallback has cost: React must track the dependency array. For SIMPLE cheap components the comparison cost > re-render cost — over-memoization makes things SLOWER. Rule: only memoize when you can measure a real performance problem.",
    },
];

const connections: Connection[] = [
    { id: "c1", source: "parent-render", target: "without-memo", protocol: "internal", latency: 5, reason: "Parent re-renders. Non-memoized child receives function prop: () => onClick() creates NEW reference. Child re-renders despite same logical output." },
    { id: "c2", source: "parent-render", target: "with-memo", protocol: "internal", latency: 5, reason: "Parent re-renders. Memoized child: React compares prev props vs current props shallowly." },
    { id: "c3", source: "without-memo", target: "use-callback", protocol: "internal", latency: 5, reason: "Problem: passing handlers as props to React.memo components requires useCallback to maintain stable references." },
    { id: "c4", source: "use-callback", target: "with-memo", protocol: "internal", latency: 5, reason: "useCallback returns same function reference if deps unchanged. React.memo shallow comparison now sees equal props." },
    { id: "c5", source: "use-memo", target: "with-memo", protocol: "internal", latency: 5, reason: "useMemo returns same object/array reference if deps unchanged. Prevents object props from defeating React.memo." },
    { id: "c6", source: "with-memo", target: "bail-out", protocol: "internal", latency: 5, reason: "Props shallowly equal! Bail-out: React skips this component entirely. Previous render output reused. Zero component function calls." },
    { id: "c7", source: "bail-out", target: "cost-warning", protocol: "internal", latency: 5, reason: "Remember: the comparison itself has cost. Only apply memoization where profiling (React DevTools Profiler) shows a real bottleneck." },
];

export function getMemoizationModuleConfig(): ModuleConfig {
    return {
        moduleId: "memoization",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_memo",
                protocol: "internal",
                label: "Memo Check",
                payload: "React.memo(ExpensiveChart)",
                sourceNodeId: "parent-render",
                targetNodeId: "with-memo",
                currentNodeId: "parent-render",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "React.memo wraps your component. Parent re-renders and passes style={{ color: 'red' }} inline. Does React.memo bail out?",
                options: [
                    { label: "Yes — the style values are the same", isCorrect: false },
                    { label: "No — {} creates a NEW object reference on every render. React.memo's shallow comparison sees different references and re-renders.", isCorrect: true },
                    { label: "Yes — React.memo does deep comparison", isCorrect: false },
                    { label: "It depends on the React version", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "React.memo uses SHALLOW comparison — it compares references for objects, not values. style={{ color: 'red' }} creates a new object on every render. Previous render had reference 0x1234, current render has 0x5678 — different references, even though the values are identical. Fix: move the object outside the component (const STYLE = { color: 'red' }) or use useMemo(() => ({ color: 'red' }), []).",
                connectionId: "c4",
                nodeId: "with-memo",
            },
        ],
        learningStory: {
            title: "The Smart Photocopier",
            content: "Memoization is like a smart photocopier that checks if the original document changed before making a new copy. A dumb photocopier makes a new copy every time you press the button, even if the document is identical. A smart photocopier (React.memo) compares the new document with the last one — if they are the same, it hands you the previous copy instead of printing again. useCallback and useMemo ensure you are handing the same document each time.",
            analogy: "A chef that remembers recipes. Without useMemo: recalculate the recipe ratios every time a dish is ordered. With useMemo: calculate once, remember the result, only recalculate when the number of servings changes. Saves work for every repeated order.",
            lookFor: "Compare WITHOUT-memo (top path) vs WITH-memo (bottom path). The without-memo path always goes through re-render regardless. The with-memo path hits Bail-out — the component is completely SKIPPED. Also notice useCallback and useMemo both feed into React.memo — all three work together!",
        },
    };
}
