import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "guest",
        name: "Guest (No Token)",
        icon: "👤",
        category: "client",
        runtime: "reactive",
        position: { x: 60, y: 120 },
        state: "idle",
        metadata: {},
        explanation: "An unauthenticated guest tries to access a protected resource. They have no JWT or session cookie. This represents an unauthenticated request — not even at the authorization stage yet. The authentication middleware must reject this before RBAC even runs.",
    },
    {
        id: "user-role",
        name: "Logged-in User (role:user)",
        icon: "🙋",
        category: "client",
        runtime: "reactive",
        position: { x: 60, y: 260 },
        state: "idle",
        metadata: {},
        explanation: "An authenticated user with role:user wants to DELETE /api/posts/123 (an admin-only action). They have a valid JWT and ARE authenticated. But authorization (RBAC) will check if their ROLE has permission for this specific action. Authentication (who are you) ≠ Authorization (what can you do).",
    },
    {
        id: "admin-role",
        name: "Admin (role:admin)",
        icon: "👑",
        category: "client",
        runtime: "reactive",
        position: { x: 60, y: 400 },
        state: "idle",
        metadata: {},
        explanation: "An authenticated admin with role:admin performs the same DELETE request. Same endpoint, same HTTP method, but different JWT payload. The RBAC middleware reads the role claim from the decoded JWT and checks it against the permission matrix for this route.",
    },
    {
        id: "auth-check",
        name: "Authentication Gate",
        icon: "🔐",
        category: "middleware",
        runtime: "event-loop",
        position: { x: 280, y: 260 },
        state: "idle",
        metadata: {},
        explanation: "First gate: Is the request authenticated at all? Extract JWT from Authorization header. Verify signature. Check expiration. If any check fails → 401 Unauthorized. If all pass → attach decoded payload to req.user and call next(). Guest requests never pass this gate.",
    },
    {
        id: "rbac-engine",
        name: "RBAC Permission Engine",
        icon: "⚖️",
        category: "middleware",
        runtime: "event-loop",
        position: { x: 480, y: 260 },
        state: "idle",
        metadata: {},
        explanation: "Second gate: Does this authenticated user's ROLE have permission for this specific action? The permission matrix: read:post → user,admin. write:post → user,admin. delete:post → admin only. edit:user → admin only. view:dashboard → admin only. The RBAC engine checks req.user.role against the required permission for this route.",
    },
    {
        id: "permission-matrix",
        name: "Permission Matrix",
        icon: "📋",
        category: "service",
        runtime: "event-loop",
        position: { x: 480, y: 120 },
        state: "idle",
        metadata: {},
        explanation: "The permission matrix maps roles to allowed actions. ADMIN: can read, write, delete, edit users, view dashboard. USER: can read, write own posts, edit own profile. GUEST: public read only. This matrix is the heart of RBAC — centralizing all permission decisions in one place. Changes to permissions require updating only the matrix, not individual route handlers.",
    },
    {
        id: "forbidden",
        name: "403 Forbidden",
        icon: "🚫",
        category: "middleware",
        runtime: "event-loop",
        position: { x: 680, y: 120 },
        state: "idle",
        metadata: {},
        explanation: "403 Forbidden: authenticated (JWT is valid) but NOT authorized (role lacks permission). This is different from 401 (not authenticated at all). Returning 403 with a clear message: 'Role user does not have permission to delete:post'. Never return 200 with an error in the body — use semantic HTTP codes.",
    },
    {
        id: "controller",
        name: "Protected Controller",
        icon: "🛡️",
        category: "service",
        runtime: "event-loop",
        position: { x: 680, y: 400 },
        state: "idle",
        metadata: {},
        explanation: "The controller only executes when BOTH authentication AND authorization have passed. By this point: we know who the user is (authentication), we know they have permission (RBAC), and we trust req.user contains valid, verified data. The controller can focus entirely on business logic without security concerns.",
    },
];

const connections: Connection[] = [
    { id: "c1", source: "guest", target: "auth-check", protocol: "http", latency: 5, reason: "Guest: no token. Auth gate immediately returns 401 Unauthorized. RBAC engine never runs." },
    { id: "c2", source: "user-role", target: "auth-check", protocol: "http", latency: 5, reason: "User: valid JWT. Auth gate verifies signature, attaches { id, role:'user' } to req.user. Calls next()." },
    { id: "c3", source: "admin-role", target: "auth-check", protocol: "http", latency: 5, reason: "Admin: valid JWT. Auth gate verifies signature, attaches { id, role:'admin' } to req.user. Calls next()." },
    { id: "c4", source: "auth-check", target: "rbac-engine", protocol: "internal", latency: 5, reason: "Authentication passed for user and admin. RBAC engine receives req.user.role and the required permission for DELETE /api/posts/:id." },
    { id: "c5", source: "rbac-engine", target: "permission-matrix", protocol: "internal", latency: 5, reason: "RBAC engine checks the permission matrix: does role:'user' have delete:post permission? Matrix says: delete:post requires role:admin." },
    { id: "c6", source: "permission-matrix", target: "forbidden", protocol: "internal", latency: 5, reason: "Role:user does NOT have delete:post. Return 403 Forbidden. The user is authenticated but not authorized. Different from 401." },
    { id: "c7", source: "permission-matrix", target: "controller", protocol: "internal", latency: 5, reason: "Role:admin DOES have delete:post. RBAC passes. Controller executes the delete operation. req.user is trusted." },
    { id: "c8", source: "controller", target: "admin-role", protocol: "http", latency: 15, reason: "200 OK: post deleted. Only the admin sees this response. Guest got 401. User got 403. Same endpoint, three different outcomes." },
];

export function getRbacModuleConfig(): ModuleConfig {
    return {
        moduleId: "rbac",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_rbac",
                protocol: "http",
                label: "DELETE /api/posts/123",
                payload: "Authorization: Bearer <admin-jwt>",
                sourceNodeId: "admin-role",
                targetNodeId: "auth-check",
                currentNodeId: "admin-role",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "Your app checks if req.user exists before allowing access to all routes. A user tries to delete someone else's post. What is missing?",
                options: [
                    { label: "Nothing — checking req.user is sufficient", isCorrect: false },
                    { label: "Authorization check: authentication proves WHO they are but not WHAT they can do. RBAC must check if their role permits delete:post", isCorrect: true },
                    { label: "A database index on the posts collection", isCorrect: false },
                    { label: "HTTPS encryption", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "Authentication (req.user exists) only proves identity. Authorization (RBAC) proves permission. A logged-in user should not be able to delete OTHER users' posts, access the admin dashboard, or modify system settings. RBAC maps roles to permissions. Without it every authenticated user is effectively an admin.",
                connectionId: "c4",
                nodeId: "rbac-engine",
            },
        ],
        learningStory: {
            title: "The Office Building Access System",
            content: "RBAC is like a corporate office building. A badge (JWT) gets you through the front door — that is authentication. But your badge only unlocks certain floors based on your role: intern badge opens floors 1-3, employee opens 1-7, manager opens 1-12, executive opens all floors. Same building, same doors, completely different access based on role.",
            analogy: "A cinema: your ticket (authentication) gets you into the building. But a standard ticket opens screens 1-5. A VIP ticket opens screens 1-5 PLUS the premium lounge. An IMAX ticket opens screen 6 only. Same venue, different permissions encoded in the ticket type (role).",
            lookFor: "Watch THREE packets enter simultaneously from three different users. The Guest packet dies at Authentication Gate. The User packet dies at RBAC Engine (403). Only the Admin packet reaches the Controller. Same endpoint, three completely different outcomes based on identity and role!",
        },
    };
}
