import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "parent",
        name: "Parent Component",
        icon: "🏠",
        category: "client",
        runtime: "reactive",
        position: { x: 300, y: 60 },
        state: "idle",
        metadata: {},
        explanation: "The Parent component owns the state that multiple children need. When state lives in the parent it can pass it DOWN as props to children and receive updates UP via callback props. The parent is the Single Source of Truth. State lifting: when two sibling components need the same data, lift the state to their closest common ancestor (the parent).",
    },
    {
        id: "parent-state",
        name: "useState (Parent)",
        icon: "💾",
        category: "service",
        runtime: "reactive",
        position: { x: 100, y: 180 },
        state: "idle",
        metadata: {},
        explanation: "State lives in the component that OWNS it and needs to update it. Rule: state should live as LOW as possible in the tree (closest to where it is used) but as HIGH as necessary (so it can be shared). If only one child needs the data, state belongs in that child. If two siblings need the same data, lift it to the parent.",
    },
    {
        id: "props-down",
        name: "Props (Read-only)",
        icon: "⬇️",
        category: "middleware",
        runtime: "reactive",
        position: { x: 300, y: 200 },
        state: "idle",
        metadata: {},
        explanation: "Props flow DOWN the component tree — parent passes data to children. Props are READ-ONLY to the child: the child CANNOT modify props directly. If a child needs to trigger a change it must call a callback prop provided by the parent. Think of props as function arguments — you receive them, you do not mutate them. Mutating props directly breaks the unidirectional data flow.",
    },
    {
        id: "child-a",
        name: "Child A (Display)",
        icon: "📺",
        category: "client",
        runtime: "reactive",
        position: { x: 100, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "Child A receives the count value as a prop and displays it. It does NOT own the state — it just renders what it receives. This is a presentational component: pure, predictable, and reusable. Give it the same props and it always renders the same output. No local state, no side effects — just UI.",
    },
    {
        id: "child-b",
        name: "Child B (Input)",
        icon: "🖊️",
        category: "client",
        runtime: "reactive",
        position: { x: 500, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "Child B receives an onChange callback prop from the parent. When the user types, Child B calls props.onChange(newValue). It does NOT update the state itself — it delegates upward. This is the 'lifting state up' pattern: the data flows down as props, events flow up as callback invocations. Never pass setState directly as a prop — wrap it in a handler function.",
    },
    {
        id: "callback-up",
        name: "Callback (Events Up)",
        icon: "⬆️",
        category: "middleware",
        runtime: "reactive",
        position: { x: 500, y: 200 },
        state: "idle",
        metadata: {},
        explanation: "Events and data changes flow UP via callback props. <ChildB onChange={(val) => setCount(val)} />. When Child B calls onChange, it triggers the parent's setter. The parent updates its state, React re-renders the parent, which passes new props to ALL children. This is React's unidirectional data flow — one direction down for data, one direction up for events.",
    },
    {
        id: "re-render-all",
        name: "Re-render Cascade",
        icon: "🌊",
        category: "service",
        runtime: "reactive",
        position: { x: 300, y: 460 },
        state: "idle",
        metadata: {},
        explanation: "When the parent state updates ALL children re-render by default (even if their specific props did not change). This is why React.memo exists — to bail out of re-renders when props are shallowly equal. The re-render cascade is: parent setState → parent re-renders → passes new props → children re-render. Understand this cascade to optimize performance with useMemo and useCallback.",
    },
];

const connections: Connection[] = [
    { id: "c1", source: "parent-state", target: "parent", protocol: "internal", latency: 5, reason: "useState hook in the parent holds the state value and setter. setCount triggers parent re-render." },
    { id: "c2", source: "parent", target: "props-down", protocol: "internal", latency: 5, reason: "Parent passes state down as props: <ChildA count={count} />. Props are immutable snapshots — read-only to the receiver." },
    { id: "c3", source: "parent", target: "callback-up", protocol: "internal", latency: 5, reason: "Parent passes callback as prop: <ChildB onChange={setCount} />. Child will call this when user acts." },
    { id: "c4", source: "props-down", target: "child-a", protocol: "internal", latency: 5, reason: "Child A receives count={42}. Renders it. Has no state of its own. Pure presentational component." },
    { id: "c5", source: "callback-up", target: "child-b", protocol: "internal", latency: 5, reason: "Child B receives onChange callback. When user types it calls props.onChange(newValue) — events flow UP." },
    { id: "c6", source: "child-b", target: "parent-state", protocol: "internal", latency: 5, reason: "User types → Child B calls onChange(newValue) → parent setState(newValue) → parent state updates → re-render cascade begins." },
    { id: "c7", source: "parent", target: "re-render-all", protocol: "internal", latency: 5, reason: "Parent re-renders with new state. All children receive new props. React diffs and updates only what changed in the DOM." },
];

export function getStatePropsModuleConfig(): ModuleConfig {
    return {
        moduleId: "state-props",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_props",
                protocol: "internal",
                label: "Props Flow",
                payload: "count={42} onChange={setCount}",
                sourceNodeId: "parent",
                targetNodeId: "props-down",
                currentNodeId: "parent",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "Two sibling components (SearchBar and ResultsList) both need the search query. Where should the state live?",
                options: [
                    { label: "In SearchBar — it is the source of the input", isCorrect: false },
                    { label: "Lifted to their parent component — the closest common ancestor that both siblings can receive props from", isCorrect: true },
                    { label: "In a global Redux store", isCorrect: false },
                    { label: "In ResultsList — it is the consumer", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "State lifting: when siblings need to share state, lift it to their closest common ancestor. SearchBar calls props.onSearch(query), which updates the parent state. The parent passes query down to ResultsList as a prop. This keeps state as local as possible while still sharing it. Only use Redux/Context when the shared state needs to cross many levels of the tree.",
                connectionId: "c6",
                nodeId: "parent-state",
            },
        ],
        learningStory: {
            title: "The Puppet Master",
            content: "Props and state are the puppet strings of React. The parent (puppet master) owns the state (the puppets position). It passes the current position DOWN as props (the strings going down to the puppet). When the puppet needs to move (user interaction), it pulls a string back UP (callback prop) to tell the master to update the position. The master updates state, and ALL puppets connected to that state update simultaneously.",
            analogy: "A TV remote control. The TV (parent) holds the current channel as state. It displays it on screen (passes to Display child as props). The remote (Input child) receives a changeChannel callback. You press a button → remote calls changeChannel(5) → TV updates its state → all displays update to show channel 5.",
            lookFor: "Data flows DOWNWARD through props-down. Events flow UPWARD through callback-up. Watch the re-render cascade at the bottom — ALL children re-render when the parent state changes. This is the unidirectional data flow that makes React predictable!",
        },
    };
}
