import type { ModuleConfig, SystemNode, Connection } from "../../engine/types/system.types";

const nodes: SystemNode[] = [
    {
        id: "app",
        name: "Application Query",
        icon: "⚡",
        category: "service",
        runtime: "event-loop",
        position: { x: 60, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "The application needs to display a blog post with its author profile and the top 3 comments. This is the classic 1:few vs 1:many decision in MongoDB schema design. How you model this determines whether you need 1 query or 3 queries to render the page.",
    },
    {
        id: "embed-doc",
        name: "Embedded Document",
        icon: "📦",
        category: "database",
        runtime: "blocking",
        position: { x: 280, y: 100 },
        state: "idle",
        metadata: {},
        explanation: "EMBED when: data is always read together, the subdocument belongs to exactly one parent (1:1 or 1:few), the embedded array has a bounded size (< 100 items), and data is written together. Example: embed an author's display name and avatar URL inside each post — this is a copy but reads are instant.",
    },
    {
        id: "embed-read",
        name: "Single Query Read",
        icon: "⚡",
        category: "database",
        runtime: "blocking",
        position: { x: 500, y: 100 },
        state: "idle",
        metadata: {},
        explanation: "Embedded data: ONE query returns the post WITH author info and comments already inside. Zero joins. Zero extra round trips. This is why MongoDB embedding is so powerful for read-heavy workloads. The entire page can render from a single db.posts.findOne({_id}) call. Performance: ~5ms.",
    },
    {
        id: "ref-doc",
        name: "Referenced Document",
        icon: "🔗",
        category: "database",
        runtime: "blocking",
        position: { x: 280, y: 340 },
        state: "idle",
        metadata: {},
        explanation: "REFERENCE when: data is shared across many documents (one author writes many posts), the related data grows unboundedly (a user's full order history), or you frequently update the referenced data (user changes their name — one update vs updating thousands of embedded copies). Reference with an ObjectId pointer — resolve with $lookup or multiple queries.",
    },
    {
        id: "ref-lookup",
        name: "$lookup / Multi-Query",
        icon: "🔄",
        category: "database",
        runtime: "blocking",
        position: { x: 500, y: 240 },
        state: "idle",
        metadata: {},
        explanation: "Referenced data requires extra work: either a $lookup (MongoDB's JOIN — expensive without index on foreignField) or separate queries: get the post, then get the author by userId, then get comments by postId. THREE database round trips = ~45ms. Trade-off: normalization prevents stale copies but costs query performance.",
    },
    {
        id: "ref-users",
        name: "Users Collection",
        icon: "🗄️",
        category: "database",
        runtime: "blocking",
        position: { x: 500, y: 400 },
        state: "idle",
        metadata: {},
        explanation: "The referenced Users collection stores a single copy of each user's profile. When the user updates their name, ONE update fixes it everywhere. With embedding, you'd need to update EVERY post document that embedded their name. Reference wins when data changes frequently or is shared across many documents.",
    },
    {
        id: "result",
        name: "Assembled Result",
        icon: "📊",
        category: "service",
        runtime: "event-loop",
        position: { x: 720, y: 220 },
        state: "idle",
        metadata: {},
        explanation: "Both approaches ultimately return the same data to the application — a post with author info and comments. The difference is entirely in HOW MANY database round trips were needed. Embed: 1 query, 5ms. Reference: 3 queries, 45ms. Choose based on your actual read/write patterns — not SQL instincts.",
    },
];

const connections: Connection[] = [
    { id: "c1", source: "app", target: "embed-doc", protocol: "db-query", latency: 5, reason: "Embed path: query the Posts collection. Author name, avatar URL, and top 3 comments are INSIDE the post document." },
    { id: "c2", source: "embed-doc", target: "embed-read", protocol: "db-query", latency: 5, reason: "Single document returned with everything embedded. No $lookup needed. Post + author info + comments in one BSON blob." },
    { id: "c3", source: "embed-read", target: "result", protocol: "internal", latency: 5, reason: "Embed result ready in ~5ms. One round trip. Application renders immediately." },
    { id: "c4", source: "app", target: "ref-doc", protocol: "db-query", latency: 5, reason: "Reference path: query the Posts collection. Returns post with only authorId and array of commentIds." },
    { id: "c5", source: "ref-doc", target: "ref-lookup", protocol: "db-query", latency: 15, reason: "$lookup on Users collection (or separate query: db.users.findOne({_id: post.authorId})). Extra round trip." },
    { id: "c6", source: "ref-lookup", target: "ref-users", protocol: "db-query", latency: 15, reason: "Second lookup: db.comments.find({postId: post._id}).limit(3). Third round trip to get referenced comments." },
    { id: "c7", source: "ref-users", target: "result", protocol: "internal", latency: 5, reason: "Reference result assembled after 3 queries, ~45ms total. Same data, 9x slower than embedded approach for this read pattern." },
];

export function getEmbedRefModuleConfig(): ModuleConfig {
    return {
        moduleId: "embed-ref",
        nodes,
        connections,
        initialPackets: [
            {
                id: "pkt_embed",
                protocol: "db-query",
                label: "Fetch Post + Author",
                payload: "db.posts.findOne({_id: postId})",
                sourceNodeId: "app",
                targetNodeId: "embed-doc",
                currentNodeId: "app",
                path: [],
                progress: 0,
                status: "pending",
                createdAt: Date.now(),
            },
        ],
        whyModePrompts: [
            {
                question: "A blog post has thousands of comments. Should you embed them in the post document?",
                options: [
                    { label: "Yes — embedding is always faster", isCorrect: false },
                    { label: "No — the document will grow past MongoDB 16MB limit and writes become expensive as the array grows unboundedly", isCorrect: true },
                    { label: "Yes — if you index the comments array", isCorrect: false },
                    { label: "No — MongoDB does not support arrays", isCorrect: false },
                ],
                correctIndex: 1,
                explanation: "Embedding unbounded arrays is a classic MongoDB anti-pattern. A popular post could have 100,000 comments — that is a 16MB document waiting to happen. Solution: separate Comments collection with a postId reference. Use $lookup or a second query to fetch comments. The 1:many relationship rule: if the many side can grow without limit, always use references.",
                connectionId: "c2",
                nodeId: "embed-read",
            },
        ],
        learningStory: {
            title: "The Sticky Note vs the Address Book",
            content: "Embedding is like a sticky note: you write the delivery address directly on the package (embed the customer address in the order). Fast to read — everything is right there. But if the customer moves, you have to update every package. Referencing is like an address book: the package has a customer ID number (reference), you look up the current address when needed. Slower to look up but always accurate.",
            analogy: "A business card (embed) vs a contacts app (reference). Business card has all info right there — instant access. But if someone changes their phone number, every card is wrong. A contacts app stores one record — update once, correct everywhere.",
            lookFor: "Compare the two paths side by side! Embed path (top): the packet goes through just 2 nodes in ~5ms. Reference path (bottom): the packet visits 4 nodes in ~45ms. Same result, radically different cost. This is the embed vs reference trade-off visualized!",
        },
    };
}
